### PR TITLE
Added whereisstreamer, moved config to new config mode

### PR DESCRIPTION
**Pull request by sakurazaki**

### CODE REVIEW

**Comment by pajlada** [comment]
no, credentials should still be stored in the env variable (https://github.com/pajbot/pajbot2-discord/pull/5#issuecomment-517926192)

**Comment by pajlada** [comment]
and for the command to be enabled, it needs to be added as an "underscore" import in main.go

**Comment by sakurazaki** [comment]
Fixed as per comments

**Comment by RAnders00** [comment]
Also i see the indentation introduces is 4 spaces while the repository uses tabs

**Pull request merged**
