### PR TITLE
$multiban: Don't add/remove reactions before user is confirmed to have permissions

### LINKED ISSUE #72: $multiban permission issues
**Describe the bug**

pajbot tells me that I don't have permission to use the $multiban command on my own server, but still reacts with the checkmark:

image

### PR DESCRIPTION
**Pull request by pajlada**
Pull request checklist:

- [x] `CHANGELOG.md` was updated, if applicable

Fixes #72

# Description

### CODE REVIEW

**Comment by pajlada** [comment]
Could you confirm this fixes #73 @alazymeme ?

**Comment by alazymeme** [comment]
This fixes 1 part of the bug, but the permission issues still remain:

image

**Comment by alazymeme** [comment]
This fixes 1 part of the bug, but the permission issue still remains:

image

**Comment by pajlada** [comment]
@alazymeme Could you try the latest commit out?

**Review by alazymeme — APPROVED** [review]

**Pull request merged**
